### ISSUE TITLE
红领巾爱学习可以刷人数嘛

### ISSUE THREAD

**Issue by Zzzz0077** [htfc786/PythonStudy-old#1]

**Comment by htfc786** [comment]
我没有理解刷人数是什么意思？帮全班人都做了？

**Comment by Zzzz0077** [comment]
对，跟青年大学习一样，一个人可以帮其他人所有人打卡，红领巾爱学习也是类似于青年大学习，有后台记录，从全国少工委微信公众号上进，底部导航那点学习二十大，就能进入专栏，作者大大有时间开发脚本代码嘛，真的很需要，有偿！！！

**Comment by htfc786** [comment]
我九年级了不需要学这个了。。。具体不是很了解，大概如下：

个人领徽章的接口是`https://hljapi.cyol.com/appassist/student/set_badge`，
![image](https://github.com/htfc786/oldcode/assets/85735251/5311b975-af7b-4303-bba2-d497e1c4dae2)
参数如上图，就是你的userid、第几季的id和章节id用他们的编码方式编码了一下，
![image](https://github.com/htfc786/oldcode/assets/85735251/97572e31-59f4-4454-9923-a55091aee36b)
userid就在localStorage里存着，通过`https://hljapi.cyol.com/appassist/student/check_user`接口获得，
![image](https://github.com/htfc786/oldcode/assets/85735251/db7e419c-52ce-4c4f-a095-6140ebb1aab6)
参数就是手机号用他们的编码方式编码了一下，

具体就没有深究了，因为我已经不学这个东西了。。。

**Comment by Zzzz0077** [comment]
作者大大，能不能开发一个程序，我们县团委需要每期刷一些数据到红领巾爱学习里面去，有偿！！！

**Comment by htfc786** [comment]
。。。真的我们九年级不用学这个了，就不研究了，实现思路就在上面了，剩下的我就不多说了
如果没有事的话我就把issue关了啊
